plugins:
  smtp_enabled:
    default: false
  smtp_address:
    default: ''
  smtp_port:
    default: '587'
  smtp_domain:
    default: ''
  smtp_user_name:
    default: ''
  smtp_password:
    default: ''
  smtp_authentication:
    default: 'login'
  smtp_enable_start_tls:
    default: true
  smtp_openssl_verify_mode:
    default: ''